FROM python:3

RUN apt-get update \
    && apt-get install -y python-lxml python-pip \
    && rm -rf /var/cache/apk/*

COPY src/requirements.txt /app/
WORKDIR /app/

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY src/ /app/

EXPOSE 5000

ENV FLASK_APP api.py

ARG HOST="0.0.0.0"
ARG PORT="5000"

ENV HOST ${HOST}
ENV PORT ${PORT}

USER 1001

CMD python api.py $API_KEY --host ${HOST} --port ${PORT} --loglevel DEBUG
