FROM python:3

RUN apt-get update \
    && apt-get install -y python-lxml python-pip \
    && rm -rf /var/cache/apk/*

COPY src/requirements.txt /app/
WORKDIR /app/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY src/ /app/

USER 1001

CMD celery -A tasks worker --loglevel=info
